before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/helm-docs
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - github:
      owner: norwoodj
      name: homebrew
    folder: Formula
    homepage: https://github.com/norwoodj/helm-docs
    description: Automatically generate markdown documentation for helm charts
    install: |
      bin.install "helm-docs"
    test: |
      system "#{bin}/helm-docs --version"
