before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - main: ./cmd/helm-docs
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
- artifacts: checksum
  args: ["-u", "<thefingerprintid>", "--output", "${signature}", "--detach-sign", "${artifact}"]

nfpms:
- vendor: helm-docs
  homepage: https://github.com/norwoodj/helm-docs
  maintainer: norwoodj
  description: A tool for automatically generating markdown documentation for helm charts
  license: GNU General Public License v3.0
  formats:
  - deb
  - rpm

brews:
  - github:
      owner: norwoodj
      name: homebrew
    folder: Formula
    homepage: https://github.com/norwoodj/helm-docs
    description: Automatically generate markdown documentation for helm charts
    install: |
      bin.install "helm-docs"
    test: |
      system "#{bin}/helm-docs --version"
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - jnorwood/{{ .ProjectName }}:latest
      - jnorwood/{{ .ProjectName }}:{{ .Tag }}
