apiVersion: v1
name: ignored
description: ingored chart
version: "0.2.0"
home: "https://github.com/norwoodj/helm-docs/example-charts/ignored"
sources: ["https://github.com/norwoodj/helm-docs/example-charts/ignored"]
engine: gotpl
maintainers:
  - email: norwood.john.m@gmail.com
    name: John Norwood
