name: Build

on:
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18.0'
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod
    - name: Setting root of the Git checkout as env
      run:
        echo PROJECT_ROOT=$(pwd) >> $GITHUB_ENV
    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --snapshot --skip-sign
    - if: always()
      run: rm -f ${HOME}/.docker/config.json
